name: PIL
publish_to: 'none' # Prevent accidental publishing to pub.dev
version: 1.0.0+2

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16 # SVG image support
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2
  video_player: ^2.8.1
  google_fonts: ^5.0.0
  http: ^1.2.2
  file_picker: ^5.2.5
  path: ^1.8.3
  mime: ^1.0.2
  http_parser: ^4.0.0
  url_launcher: ^6.0.20
  intl: ^0.18.0
  shared_preferences: ^2.2.0
  flutter_pdfview: ^1.3.2
  universal_html: ^2.0.7
  path_provider: ^2.0.14
  flutter_spinkit: ^5.1.0
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: false # Disable other platforms to focus on Android
  web: false
  windows: false
  macos: false
  image_path: "assets/app_icon.png"

#  adaptive_icon_background: "#ffffff"
#  adaptive_icon_foreground: "lib/assets/images/pillogo2.png"





#  ios: false
#  web: false
#  windows: false
#  macos: false

flutter:
  uses-material-design: true

  # Asset declaration: Include specific images
  assets:
    - lib/assets/images/images.jpeg
    - lib/assets/images/logoimg.png
    - lib/assets/images/logoimage.png
    - lib/assets/images/getstarted.png
    - lib/assets/images/admissionopen.png
    - lib/assets/images/imggetstarted.png
    - lib/assets/images/heart.png
    - lib/assets/images/profile.png
    - lib/assets/images/approved.png
    - lib/assets/images/admicon.png
    - lib/assets/images/homeicon.png
    - lib/assets/images/bannerimg1.png
    - lib/assets/images/bannerimg2.png
    - lib/assets/images/bannerimg3.png
    - lib/assets/images/pending.png
    - lib/assets/images/pending.png
    - assets/app_icon.png
    - lib/assets/images/discovr.png
    - lib/assets/images/telephone.png
    - lib/assets/images/cirricicon.png
    - lib/assets/images/labicon.png
    - lib/assets/images/hatsicon.png
    - lib/assets/images/pillogo.png
    - lib/assets/images/pillogo2.png
    - lib/assets/images/btcbanner.png
    - lib/assets/images/schooladmissionbanner.png
    - lib/assets/images/buildicon.png
    - lib/assets/images/onlineicon.png
    - lib/assets/images/messageicon.png
    - lib/assets/images/missioniconlogo.png
    - lib/assets/images/pagal.png
    - lib/assets/images/missionandvision.png
    - lib/assets/images/banner2.png
    - lib/assets/images/locationicon.png
    - lib/assets/images/getstartedpage.png
    - lib/assets/images/3.png
    - lib/assets/images/reading.png
    - lib/assets/images/syllicon.png
    - lib/assets/images/female.png
    - lib/assets/images/btcschool.png
    - lib/assets/images/schooladmin.jpg
    - lib/assets/images/galleryicon.png
    - lib/assets/images/missicon.png
    - lib/assets/images/annualday.jpg
    - lib/assets/images/building.png
    - lib/assets/images/like.png
    - lib/assets/vectors/nav-logo.svg
    - lib/assets/vectors/logoimg.svg
    - lib/assets/videos/poineervideo.mp4
    - lib/assets/videos/pilvideo.mp4

  # Fonts (optional example, remove if not needed)
  fonts:
    - family: Sans
      fonts:
        - asset: lib/assets/fonts/opensansbold.ttf

    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Robotomedium.ttf
          weight: 400
    - family: FairPlay
      fonts:
        - asset: lib/assets/fonts/PlayfairDisplay-Bold.ttf
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Bold.ttf
